algoritmo "exe14"
var
a,b,c :inteiro
s :real
// soma ficou real por causa da potencia ^

inicio
//entrada de dados
escreva ("valor de a")
leia(a)
escreva ("valor de b ")
leia (b)
escreva ( "valor de c")
leia (c)

//processamento
// outra forma de resolver
// s <- exp ( ( a + b+ c ), 2) (qaundo faz assim a , siginifica elevado ( ex , 2)

s <- (a + b + c )^ 2

//saida
escreval ( "soma = " , s)

fimalgoritmo