algoritmo " exenumero5"

var

   num1 , num2 :real
   soma,sub,multi,divi :real

inicio
   //entrada

   escreva ( "escreva um numero:")
   leia (num1)

   escreva ( " escreva um numero:")
   leia (num2)

   //processamento

   soma <- num1 + num2
   sub <- num1 - num2
   multi <- num1 * num2
   divi <- num1 / num2

   //saida

   escreval ("soma :",soma)
   escreval ("sub:" ,sub)
   escreval ( "multi:" ,multi)
   escreval ( "divi:",divi)



fimalgoritmo