algoritmo "exercicio3_2"
var
 n1 , n2 , total :inteiro

inicio
  //entrada de dados
  escreva ("digite um numero:")
  leia (n1)

  escreva ("digite um numero:")
  leia (n2)

  //processamento

  total <- n1 + n2
   escreval ( "soma = " ,total )

  total <- n1 - n2
  escreval ("subtracao = " ,  total )

  total <- n1 * n2
    escreval (" multiplicacao =" , total)




fimalgoritmo