algoritmo "exercicio3_1"
var
 n1 , n2 ,soma ,subtracao,multiplicacao :inteiro

inicio
  //entrada de dados
  escreva ("digite um numero:")
  leia (n1)

  escreva ("digite um numero:")
  leia (n2)

  //processamento
  soma <- n1 + n2
  subtracao <- n1 - n2
  multiplicacao <- n1 * n2

  // saida de dados
  escreval ( " soma = " , soma)
  escreval ( " subtracao = " ,subtracao)
  escreval ( " multilicacao = " ,multiplicacao)
fimalgoritmo