algoritmo "exercicio3_4"
var
 n1 , n2 ,n3, total :inteiro

inicio
  //entrada de dados
  escreva ("digite um numero:")
  leia (n1)

  escreva ("digite um numero:")
  leia (n2)
  
  escreva ("digite um numeo")
  leia (n3)

  //processamento

  total <- n1 + n2 + n3
   escreval ( "soma = " ,total )

  total <- n1 - n2 - n3
  escreval ("subtracao = " ,  total )

  total <- n1 * n2 * n3
    escreval (" multiplicacao =" , total)




fimalgoritmo