Algoritmo " experimento graus celsius em Fah"

Var
 c ,f :real


Inicio
   escreval (" temperatura em celsus ")
   leia (C)
   
    //processamento
   
   f <-(9*c +160)/5
   
   se (f > 45) e (f <90) entao
   escreval (" tempertura ideal para o experimento")
   
   senao
    escreval ("temperatura inapropiada para o experimento")
   
   fimse

     escreval ( "fah ", f)
Fimalgoritmo