Algoritmo "numeromaior"

Var
   a ,b :real

Inicio

   //entrada de dados

   escreval ("valor de a ")
   leia (a)
   escreval ("valor de b")
   leia (b)
   
   //processamento descobrir o numero maior
   
   se a > b então
   escreval (" a é maior :", a)

   senão

    se b > a então
   escreval  (" b é maior :" , b)
   
  senao
   escreval ("a e  b são iguais")
   
   fimse
   fimse

Fimalgoritmo