Algoritmo "parouimpar"

Var

   numero:inteiro

Inicio

   escreval ("digite um numero ")
   leia (numero)
   // como saber se esse numero é par ou impar,se é divisivel ou multiplo por outro
    // se eu quisesse saber o resto:
    // resto<- numero mod 2
    //escreval("reto",resto)


   se (numero mod 2 =0 )então
      escreval ( "esse numero é par")

   senao
      escreval ("esse numero é impar ")

   fimse

Fimalgoritmo